import Head from "next/head";
import React from "react";
import getAnimeQuery from "../requests";
import AnimeCard from "../components/AnimeCard";
import Header from "../components/Header";
import { useSelector, useDispatch } from "react-redux";
import { trending, season } from "../store/mainSlice";
import Footer from "../components/Footer";

export default function Home() {
  const categorie = useSelector((state) => state.main.categorie);

  const [animes, setAnimes] = React.useState([]);
  React.useEffect(() => {
    const get = async () => {
      const data = await categorie();
      setAnimes(data);
    };
    get();
  }, [categorie]);

  return (
    <div>
      <Head>
        <title>Hulu Anime</title>
        <meta name="Hulu Anime" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="bg-[#0D1C23]">
        <div
          className="grid py-8 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 
                        xl:grid-cols-5 2xl:grid-cols-6 3xl:grid-cols-7 gap-4  
                        w-[360px] sm:w-[440px] md:w-[660px] lg:w-[860px] xl:w-[1080px] 
                        2xl:w-[1300px] 3xl:w-[1400px] m-auto"
        >
          {animes.map((anime) => (
            <AnimeCard key={anime.id} anime={anime} />
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
}
